# Site settings
title: josh lives here
timezone: Australia/Sydney
description: A site by a guy called Josh
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://josh64x2.github.io" # the base hostname & protocol for your site
github_username: josh64x2 

# Build settings
markdown: kramdown
show_drafts: false
future: true 

gems:
  - jekyll-feed
